### PR TITLE
(GH-29) Use regex to validate token file input

### LINKED ISSUE #29: Deprecation warning for `URI.escape` in config
## Describe the Bug
Starting with Ruby 2.7, the `URI.escape` emits a deprecation warning:

```
opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/orchestrator_client-0.5.1/lib/orchestrator_client/config.rb:101: warning: URI.escape is obsolete
```

This method is used in the config class here: https://github.com/puppetlabs/orchestrator_client-ruby/blob/master/lib/orchestrator_client/config.rb#L101

### PR DESCRIPTION
**Pull request by lucywyman**
Previously we were using `URI.escape` to [verify that the provided
tokenfile path configuration didn't contain illegal
characters](https://github.com/puppetlabs/orchestrator_client-ruby/commit/3f100911622a94b80edebf8a976620b1edfc3993).
The method now raises a warning when called [as of
Ruby2.7](https://stackoverflow.com/questions/65423458/ruby-2-7-says-uri-escape-is-obsolete-what-replaces-it),
but the Orchestrator client was only using the function to verify that
no illegal characters were in the provided string. The way that
`URI.escape` worked [by default was using the 
constant](https://stackoverflow.com/questions/34274838/why-is-uri-escape-marked-as-obsolete-and-where-is-this-regexpunsafe-constant)
`URI::UNSAFE` which is a regex to scan for illegal characters. Rather
than having to do [piecemeal URI
validation](https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string)
we can simply use the `URI::UNSAFE` constant to check the string in the
same way we were before.

This also pulls in #22 and rebases so there's no merge conflict.

Closes #29

### CODE REVIEW

**Comment by donoghuc** [comment]
Did we ever have automated tests for this repo?

**Review by donoghuc — APPROVED** [review]
As long as the spec test is passing for this i'm :+1:

**Comment by lucywyman** [comment]
Yeah, [you actually added a test for this case when it was first implemented](https://github.com/puppetlabs/orchestrator_client-ruby/commit/3f100911622a94b80edebf8a976620b1edfc3993) so I think should be good. No behavior change, so I don't think it needs any modification.

**Comment by donoghuc** [comment]
Am i just missing *where* that test is being run?

**Review by beechtom — APPROVED** [review]

**Comment by lucywyman** [comment]
Hmm, yeah, I don't think I can trigger the workflow on this PR, but the tests at least pass for me locally 😬

**Review by donoghuc — APPROVED** [review]

File: lib/orchestrator_client/config.rb [hunk 1]
```diff
@@ -98,7 +98,8 @@ def load_token
     else
       validate_file('token-file', config['token-file'])
       token = File.open(config['token-file']) { |f| f.read.strip }
-      if token != URI.escape(token)
+      # If the token file contains illegal characters
+      if token =~ URI::UNSAFE
```
Comment (MikaelSmith) [inline lib/orchestrator_client/config.rb:102]: As a security practice, we know the format of the token file. We could specifically check it only contained expected characters.

In this instance, the current check is probably sufficient.
